-- AlterTable
ALTER TABLE "User" ADD COLUMN     "aiTokens" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "isPremium" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "lastTokenReset" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "subscriptionEnd" TIMESTAMP(3);
